version: '3'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  linter:
    image: buildkite/plugin-linter
    command: ['--id', 'fclabs/git-clone-with-branch']
    volumes:
      - ".:/plugin:ro"